#!/usr/bin/env bash
set -e

./keep-sudo
./packages

# Create entrypoint script for addiotional steps after toolbox is started (to run as user, instead of root)
cp .entrypoint.sh $HOME/.entrypoint.sh
chmod +x $HOME/.entrypoint.sh
