#!/usr/bin/env bash
set -euo pipefail

# Use util lib
source $(dirname $0)/../base/utils

echo "Install packages"

if [ -f "/bin/dnf" ]; then
    package_list=" \
        make \
        vim \
        openssl \
        git \
        httpie \
        golang \
        git-lfs \
        bind-utils \
        nodejs \
        python37 \
        python3-devel \
        python3-setuptools \
        python3-pip 
    "
    dnf upgrade -y
    dnf install -y $package_list
elif [ -f "/usr/bin/apt-get" ]; then
   package_list="\
    build-essential \
    software-properties-common \
    vim \
    curl \
    wget \
    libssl-dev \
    git \
    httpie \
    git-lfs \
    bind9 bind9utils bind9-doc dnsutils \
    python3-dev \
    python3-setuptools \
    python3-pip 
"
    apt-get update
    apt-get install -y $package_list
fi