#!/usr/bin/env bash
set -euo pipefail

echo "Install packages"

dnf install -y \
    make \
    vim \
    openssl \
    git \
    httpie \
    golang \
    git-lfs \
    bind-utils \
    python3 \
    python3-pip

