#!/usr/bin/env bash
set -euo pipefail

echo "Install packages"

dnf upgrade -y

dnf install -y \
    make \
    vim \
    openssl \
    git \
    httpie \
    golang \
    git-lfs \
    bind-utils \
    nodejs \
    python37 \
    python3-devel \
    python3-setuptools \
    python3-pip 


