#!/usr/bin/env bash
set -eu

#ln -sf /usr/bin/python3.7 /usr/bin/python3
#pip3 install --no-cache-dir --upgrade pip setuptools wheel
#python3 -m pip install --no-cache-dir azure-cli
#az extension add --yes --name azure-devops  


# dnf install -y azure-cli

curl -L https://aka.ms/InstallAzureCli | bash


az extension add --yes --name azure-devops
