#!/usr/bin/env bash
set -e

# Use util lib
source $(dirname $0)/../base/utils

echo "Install golang"

# Use util lib
source $(dirname $0)/../base/utils


if [ -f "/usr/bin/apt-get" ]; then
    add-apt-repository -y ppa:longsleep/golang-backports
    apt update
fi

install_packages golang
