#!/usr/bin/env bash
set -e

echo "Install kubectl"

if [ -d "/etc/yum.repos.d" ]; then
    cat <<EOF > /etc/yum.repos.d/kubernetes.repo
    [kubernetes]
    name=Kubernetes
    baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
    enabled=1
    gpgcheck=1
    repo_gpgcheck=1
    gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
EOF
  
elif [ -d "/etc/apt/sources.list.d/" ]; then
    curl -fsSLo /usr/share/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg
    echo "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | tee /etc/apt/sources.list.d/kubernetes.list
fi

if [ -f "/bin/dnf" ]; then
    dnf upgrade -y
    dnf install -y kubectl
elif [ -f "/usr/bin/apt-get" ]; then
    apt-get update
    apt-get install -y kubeadm kubelet kubectl kubernetes-cni
fi
