#!/usr/bin/env bash
set -eu

echo "Install vscode"


if [ -d "/etc/yum.repos.d" ]; then
    rpm --import https://packages.microsoft.com/keys/microsoft.asc
    sh -c 'echo -e "[code]\nname=Visual Studio Code\nbaseurl=https://packages.microsoft.com/yumrepos/vscode\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" > /etc/yum.repos.d/vscode.repo'

elif [ -d "/etc/apt/sources.list.d/" ]; then
    curl -sSL https://packages.microsoft.com/keys/microsoft.asc | apt-key add -
    add-apt-repository "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main"
fi

package_list=" \
    libX11-xcb \
    libdrm \
    libgbm \
    code
"

if [ -f "/bin/dnf" ]; then
    dnf upgrade -y
    dnf install -y libX11-xcb \
        libdrm \
        libgbm \
        code
elif [ -f "/bin/yum" ] || [ -f "/usr/bin/yum" ]; then
    yum upgrade
    yum install -y $package_list
elif [ -f "/usr/bin/apt-get" ]; then
    apt-get install -y \
        code
fi

echo -e "[INFO]\t Adding extensions to entrypoint script"
cat <<EOF >> $HOME/.entrypoint.sh
code --install-extension ms-python.python 
code --install-extension esbenp.prettier-vscode
code --install-extension vscode-icons-team.vscode-icons
code --install-extension alphabotsec.vscode-eclipse-keybindings
code --install-extension golang.Go
code --install-extension MS-vsliveshare.vsliveshare
code --install-extension redhat.vscode-yaml
code --install-extension zhuangtongfa.Material-theme
code --install-extension DavidAnson.vscode-markdownlint
code --install-extension yzhang.markdown-all-in-one
code --install-extension wholroyd.jinja
EOF