FROM docker.io/library/ubuntu:20.04

ARG BUILD_DATE
ARG IMAGE_VERSION
ARG DEBIAN_FRONTEND=noninteractive

LABEL org.opencontainers.image.created="$BUILD_DATE" \
      org.opencontainers.image.authors="Sezgin Ceyhan" \
      org.opencontainers.image.url="https://github.com/sezginceyhan/toolboxes" \
      org.opencontainers.image.documentation="https://github.com/sezginceyhan/toolboxes" \
      org.opencontainers.image.source="https://github.com/sezginceyhan/toolboxes" \
      org.opencontainers.image.version="$IMAGE_VERSION" \
      org.opencontainers.image.title="Cloud development image" \
      org.opencontainers.image.description="Development environment"

COPY scripts/base /tmp/scripts/base

WORKDIR /tmp/scripts/base

RUN /tmp/scripts/base/install

COPY scripts/apps /tmp/scripts/apps

WORKDIR /tmp/scripts/apps

# RUN /tmp/scripts/apps/install \
#     && rm -rf /tmp/scripts \
#     && rm -rf /var/lib/apt/lists/*
 
CMD [ "/bin/zsh" ]
